language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
- "pip install -r requirements.txt"
- "pip install -r dev/requirements-test.txt"
- "pip install python-coveralls"

sudo: false

script:
  - "python setup.py test"

after_success:
  - "coveralls"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#icspy"
    use_notice: false
    skip_join: true
    template:
      - "build#%{build_number} (%{branch} - %{commit}): %{message}"
